### ISSUE TITLE
Problem with useTranslator() hook

### ISSUE THREAD

**Issue by taZik616** [KoreanThinker/react-native-translator#5] opened 2022-04-27 10:32 UTC
When I used this hook in a project it didn't work. I created a new react native project to make sure that the error is not due to the fact that there is something problematic in that project. I ended up getting the same error.
There is an error on android (I can’t find out if the module works on ios)
![изображение_2022-04-27_153042702](https://user-images.githubusercontent.com/94304770/165498979-fc64c768-26d8-4acb-96d7-6d6f4032f6e0.png)
![изображение_2022-04-27_153138476](https://user-images.githubusercontent.com/94304770/165499144-02f5e1dd-992f-4053-9c28-bdd21152672d.png)

**Comment by KoreanThinker** [comment] 2022-04-27 13:48
Duplicate of #3

**Closed** 2022-04-27 13:48 UTC
